/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenitRouteImport } from './routes/zenit'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as DesarrollosRouteImport } from './routes/desarrollos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ZenitRoute = ZenitRouteImport.update({
  id: '/zenit',
  path: '/zenit',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrollosRoute = DesarrollosRouteImport.update({
  id: '/desarrollos',
  path: '/desarrollos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/desarrollos': typeof DesarrollosRoute
  '/nosotros': typeof NosotrosRoute
  '/zenit': typeof ZenitRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/desarrollos': typeof DesarrollosRoute
  '/nosotros': typeof NosotrosRoute
  '/zenit': typeof ZenitRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/desarrollos': typeof DesarrollosRoute
  '/nosotros': typeof NosotrosRoute
  '/zenit': typeof ZenitRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/desarrollos'
    | '/nosotros'
    | '/zenit'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contacto'
    | '/desarrollos'
    | '/nosotros'
    | '/zenit'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/desarrollos'
    | '/nosotros'
    | '/zenit'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DesarrollosRoute: typeof DesarrollosRoute
  NosotrosRoute: typeof NosotrosRoute
  ZenitRoute: typeof ZenitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zenit': {
      id: '/zenit'
      path: '/zenit'
      fullPath: '/zenit'
      preLoaderRoute: typeof ZenitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrollos': {
      id: '/desarrollos'
      path: '/desarrollos'
      fullPath: '/desarrollos'
      preLoaderRoute: typeof DesarrollosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DesarrollosRoute: DesarrollosRoute,
  NosotrosRoute: NosotrosRoute,
  ZenitRoute: ZenitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
